<a href="https://colab.research.google.com/github/wnsmir/DSBA5/blob/main/Day1Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
mid_scores = np.array([10, 20, 30])
final_scores = np.array([60, 70, 80])

In [3]:
total = (mid_scores + final_scores) / 2
print(total)

[35. 45. 55.]


In [4]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [5]:
a.shape

(3,)

In [6]:
a.ndim

1

In [7]:
a.dtype

dtype('int64')

In [10]:
score = np.array([10, 20, 30, 40, 50, 60])
score[1:4]

array([20, 30, 40])

In [11]:
#2차원 구조
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
arr2.shape

(2, 3)

In [13]:
arr2.ndim

2