<a href="https://colab.research.google.com/github/wnsmir/DSBA5/blob/main/Day2Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
y = [[1,2,3],[4,5,6],[7,8,9]]

In [3]:
y

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np_array = np.array(y)
np_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
print(np_array.shape)
print(np_array.ndim)
print(np_array.dtype)

(3, 3)
2
int64


In [9]:
np_array[2,2]

9

In [10]:
np_array = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
np_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [11]:
np_array[0:2,2:4]

array([[3, 4],
       [7, 8]])

In [15]:
np_array[0,:]

array([1, 2, 3, 4])

In [16]:
np_array[1,1:3]

array([6, 7])

In [17]:
np_array[np_array>5] # 5보다 큰 원소들만 뽑아냄

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [19]:
np.array(range(5))
np.arange(5)

array([0, 1, 2, 3, 4])

In [20]:
y = np.arange(12)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [21]:
yy = y.reshape(3,4)
yy

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
yyy = y.reshape(-1,4)
yyy

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
yyyy = y.reshape(-1,1)
yyyy

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [26]:
yyyy.flatten() # 1차원으로 만들어줌

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])