<a href="https://colab.research.google.com/github/wnsmir/DSBA5/blob/main/Day3%ED%8C%8C%EC%9D%B4%EC%8D%AC%EC%B5%9C%EC%A2%85.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 1. enumerate

In [ ]:
some_list=['foo','bar','baz']
for v in some_list:
  print(v)

foo
bar
baz


In [ ]:
some_list=['foo','bar','baz']
mapping={} # null dict type
for i,v in enumerate(some_list):
  mapping[v]=i
print(mapping)

{'foo': 0, 'bar': 1, 'baz': 2}


In [ ]:
# 2. zip
seq1=['foo','bar','baz']
seq2=['one','two','three']

In [ ]:
zip1=list(zip(seq1,seq2))

In [ ]:
print(zip1)

[('foo', 'one'), ('bar', 'two'), ('baz', 'three')]


In [ ]:
zip1[2]

('baz', 'three')

In [ ]:
seq1=['foo','bar','baz']
seq2=['one','two','three']
seq3=[False,True]
list(zip(seq1,seq2,seq3)) # 가장 짧은 크기를 따른다.

[('foo', 'one', False), ('bar', 'two', True)]

In [ ]:
# 3. map 함수
def ftn1(x):
  return x**2
ftn1(100)

10000

In [ ]:
numbers=[1,2,3,4,5]
ftn1(numbers)

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [ ]:
res=[]
for v in numbers:
  res.append(ftn1(v))
print(res)

[1, 4, 9, 16, 25]


In [ ]:
res=list(map(ftn1,numbers))
print(res)

[1, 4, 9, 16, 25]


In [ ]:
numbers1=[1,2,3]
numbers2=[4,5,6]
result=list(map(lambda x,y:x+y,numbers1,numbers2))
print(result)

[5, 7, 9]


In [ ]:
## numpy
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.zeros_like(a)

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.ones_like(a)

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
### identity matrix : 단위행렬
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
### 연산
np.sqrt(2)

1.4142135623730951

In [ ]:
ar1=np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
ar2=np.random.randn(10)
print(ar2)

[ 0.39126982 -1.38610223 -0.76420442  0.72470724 -1.70311816  1.84579358
 -0.53909797 -0.08875536  0.19116399  0.36632365]


In [ ]:
### abs, sqrt, exp, log, log10, sign

In [ ]:
np.sign(ar2)

array([ 1., -1., -1.,  1., -1.,  1., -1., -1.,  1.,  1.])

In [ ]:
np.log(10)

2.302585092994046

In [ ]:
np.log10(10)

1.0

In [ ]:
np.sign(-3)

-1

In [ ]:
# np.ceil, np.floor, np.rint, np.int64

In [ ]:
a=np.array([1.3,1.5])
np.ceil(a)

array([2., 2.])

In [ ]:
np.floor(a)

array([1., 1.])

In [ ]:
np.rint(a)

array([1., 2.])

In [ ]:
np.int64(a)

array([1, 1])

In [ ]:
## np.isnan, np.isfinite, isinf
a=np.array([1.0,np.nan,3.5,np.nan])
a

array([1. , nan, 3.5, nan])

In [ ]:
np.isnan(a)

array([False,  True, False,  True])

In [ ]:
a=np.array([1.0,np.inf, 1.5,-np.inf])
a

array([ 1. ,  inf,  1.5, -inf])

In [ ]:
np.isfinite(a)

array([ True, False,  True, False])

In [ ]:
np.isinf(a)

array([False,  True, False,  True])

In [ ]:
abs(a)

array([1. , inf, 1.5, inf])

In [ ]:
## any 함수
a=np.array([True,False,True])
np.any(a)

True

In [ ]:
a=np.array([False,False,False])
np.any(a)

False

In [ ]:
## all 함수
a=np.array([True,False,True])
np.all(a)

False

In [ ]:
a=np.array([True,True,True])
np.all(a)

True

In [ ]:
### axis=0, axis=1

In [ ]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a.mean()

3.5

In [ ]:
a.mean(axis=0)

array([2.5, 3.5, 4.5])

In [ ]:
a.mean(axis=1)

array([2., 5.])

In [ ]:
a.sum(axis=0)

array([5, 7, 9])

In [ ]:
a.sum(axis=1)

array([ 6, 15])

In [ ]:
## cumsum
print(a)
a.cumsum(axis=0)

[[1 2 3]
 [4 5 6]]


array([[1, 2, 3],
       [5, 7, 9]])

In [ ]:
a.cumsum(axis=1)

array([[ 1,  3,  6],
       [ 4,  9, 15]])

In [ ]:
### np.min, np.max, np.argmin, np.argmax

In [ ]:
a=np.array([[10,20,30],[40,50,60]])
a

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
np.min(a,axis=0)

array([10, 20, 30])

In [ ]:
np.min(a,axis=1)

array([10, 40])

In [ ]:
np.argmin(a,axis=0)

array([0, 0, 0])

In [ ]:
np.argmin(a,axis=1)

array([0, 0])

In [ ]:
np.argmax(a,axis=0)

array([1, 1, 1])

In [ ]:
np.argmax(a,axis=1)

array([2, 2])

In [ ]:
### np.where
a=np.array([3,-3,5,0,-5])
a

array([ 3, -3,  5,  0, -5])

In [ ]:
b=np.where(a>0,a,0)
b

array([3, 0, 5, 0, 0])

In [ ]:
a=np.array([[1,-2,3],[2,-4,5]])
a

array([[ 1, -2,  3],
       [ 2, -4,  5]])

In [ ]:
b=np.where(a>0,a,0)
b

array([[1, 0, 3],
       [2, 0, 5]])

In [ ]:
a=np.array([1,2,3,np.nan])
a

array([ 1.,  2.,  3., nan])

In [ ]:
np.where(np.isnan(a),0,a)

array([1., 2., 3., 0.])

In [ ]:
(np.isnan(a)).sum()

1

In [ ]:
## 선형대수 : 행렬연산
x=np.array([[1,2,3],[4,5,6]])
y=np.array([[6,23],[-1,7],[8,9]])
print(x)
print(y)

[[1 2 3]
 [4 5 6]]
[[ 6 23]
 [-1  7]
 [ 8  9]]


In [ ]:
## 행렬의 곱
x.dot(y)  ## x y

array([[ 28,  64],
       [ 67, 181]])

In [ ]:
np.dot(x,y)

array([[ 28,  64],
       [ 67, 181]])

In [ ]:
np.sum(x,axis=1)

array([ 6, 15])

In [ ]:
np.dot(x,np.ones(3))

array([ 6., 15.])

In [ ]:
## inv((yTy)-1)

In [ ]:
from numpy.linalg import inv

In [ ]:
np.linalg.inv(y.T.dot(y))

array([[ 0.02599606, -0.00800789],
       [-0.00800789,  0.00398422]])

In [ ]:
inv(y.T.dot(y))

array([[ 0.02599606, -0.00800789],
       [-0.00800789,  0.00398422]])

In [ ]:
### numpy 에서 난수(random number) 생성

In [ ]:
np.random.seed(12345)
np.random.rand(10)

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [ ]:
np.random.seed(123)
np.random.rand(5)

### 여기까지 실습! 15시까지 휴식!

array([0.69646919, 0.28613933, 0.22685145, 0.55131477, 0.71946897])

In [ ]:
import random
a=[1,2,3,'aa',4,5]
random.choice(a)

4

In [ ]:
random.choices(a,k=3) # 복원추출 : sampling with replacement

[4, 5, 5]

In [ ]:
random.sample(a,k=5) # 비복원추출 : sampling without replacement

[5, 1, 4, 'aa', 3]

In [ ]:
x=[]
for i in range(10):
  b=random.random()
  x.append(b)
print(x)

[0.3891344948064014, 0.38639855720954985, 0.7365105299674716, 0.7335750725683714, 0.8768695015904435, 0.5212354949307234, 0.8499646995279089, 0.659868948166257, 0.7354292588962066, 0.3936531978491151]


In [ ]:
a=np.array([1,2,3,4,5])
np.random.choice(a,3,replace=True) # 복원추출 : sampling with replacement

array([1, 2, 2])

In [ ]:
a=np.array([1,2,3,4,5])
np.random.choice(a,3,replace=False) # 비복원추출 : sampling without replacement

array([4, 2, 5])

In [ ]:
a=[1,2,3,'aa',4,5]
random.shuffle(a)
a

[5, 2, 4, 1, 3, 'aa']

In [ ]:
a=np.array([1,2,3,4,5])
np.random.shuffle(a)
a

array([1, 5, 3, 4, 2])

In [ ]:
#### 문자열 처리
s='Python love!'

In [ ]:
s[-1]

'!'

In [ ]:
## split 함수 : 문자열 분리
s='Welcome to Python'
s.split()

['Welcome', 'to', 'Python']

In [ ]:
s='2021.8.15'
s.split('.')

['2021', '8', '15']

In [ ]:
s='Hello, World!'
res=s.split(',')

In [ ]:
s1=[]
for x in res:
  s1.append(x.strip())
s1

['Hello', 'World!']

In [ ]:
[x.strip() for x in s.split(',')]

['Hello', 'World!']

In [ ]:
## 문자열 이어붙이기

In [ ]:
''.join(['apple','grape','banana'])

'applegrapebanana'

In [ ]:
' '.join(['apple','grape','banana'])

'apple grape banana'

In [ ]:
'.'.join(['apple','grape','banana'])

'apple.grape.banana'

In [ ]:
'-'.join(['apple','grape','banana'])

'apple-grape-banana'

In [ ]:
## replace
'010.1234.5678'.replace('.','-')

'010-1234-5678'

In [ ]:
s='hello world'
''.join(list(s))

'hello world'

In [ ]:
list(s)

['h', 'e', 'l', 'l', 'o', ' ', 'w', 'o', 'r', 'l', 'd']

In [ ]:
s='Actions \n\t speak louder than words'
print(s)

Actions 
	 speak louder than words


In [ ]:
' '.join(s.split())

'Actions speak louder than words'

In [ ]:
s='Hello, World!'
s.lower()

'hello, world!'

In [ ]:
s='Hello, World!'
s.upper()

'HELLO, WORLD!'

In [ ]:
s='hello, world!'
s.capitalize()

'Hello, world!'

In [ ]:
s='    hello, world     '
s.strip()

'hello, world'

In [ ]:
s.lstrip()

'hello, world     '

In [ ]:
s.rstrip()

'    hello, world'

In [ ]:
s='############hellow, world####################'
s.strip('#')

'hellow, world'

In [ ]:
s.lstrip('#')

'hellow, world####################'

In [ ]:
s.rstrip('#')

'############hellow, world'

In [ ]:
s='www.book.sr.co.kr'
s.find('.kr')

14

In [ ]:
s.find('x')

-1

In [ ]:
s.count('.')

4

In [ ]:
## 정규표현식 (regular expression)
## 메타문자

*   ^ : 문자열의 시작을 의미
*   $ : 문자열의 끝을 의미
*   . : 모든 문자를 의미
*   \d : 숫자를 의미
*   \w : 숫자+영문자+한글문자를 의미
*   \s : 공백문자 (스페이스, 탭, 줄바꿈)
*   \S : 공백제외 모든 문자
*  '*'  : 앞 문자가 0번 이상 반복
*  '+' : 앞 문자가 1번이상 반복
*   ?  : 앞에 있는 문자열이 없거나, 1개 {0,1}임을 의미
*  [abc] : a,b,c, 가운데 하나의 문자
*  [^abc] : a,b,c, 가 아닌 어떤 자
*  {m,n} : m에서 n까지 반복
*  | : or 연산자

In [ ]:
import re
text='foo bar\t baz \tqux'
regex=re.compile('\S.')
regex.findall(text)

['fo', 'o ', 'ba', 'r\t', 'ba', 'z ', 'qu']

In [ ]:
import re
text='CAABBB'
regex=re.compile('AB*')
regex.findall(text)

['A', 'ABBB']

In [ ]:
import re
text='CA AB BB'
regex=re.compile('ab+',re.I)
regex.findall(text)

['AB']

In [ ]:
import re
text='CB ABBB BB'
regex=re.compile('[CA].')
regex.findall(text)

['CB', 'AB']

In [ ]:
import re
text='CB ABBB BB'
regex=re.compile('B{1,3}.')
regex.findall(text)

['B ', 'BBB ', 'BB']

In [ ]:
import re
text='오늘은 7월9일이고, 내 전화번호는 010-1234-5678입니다.'
regex=re.compile('010-[0-9]{3,4}-[0-9]{4}')
regex.findall(text)
re.sub(regex, '***-****-****',text)

'오늘은 7월9일이고, 내 전화번호는 ***-****-****입니다.'

In [ ]:
import re
text='abc@facebook.com와 bbc@google.com에서 이메일이 도착했습니다.'
regex=re.compile('\S+@[a-z.]+')
print(regex.findall(text))
re.sub(regex, '***@***',text)

['abc@facebook.com', 'bbc@google.com']


'***@***와 ***@***에서 이메일이 도착했습니다.'

In [ ]:
import re
text='Good morning! RT @PythonUser I like Python #Python'
regex=re.compile('RT|@\S+|#\S+')
print(regex.findall(text))
text1=re.sub(regex,'',text)
print(text1)
text2=re.sub("\s+"," ",text1)
print(text2)

['RT', '@PythonUser', '#Python']
Good morning!   I like Python 
Good morning! I like Python 
